// <auto-generated />
using System;
using Edc.Backend.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Edc.Backend.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428223527_AddTenantEdcCredentials")]
    partial class AddTenantEdcCredentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Edc.Backend.Api.Infrastructure.Persistence.EdcLinkReading", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ProducerEan")
                        .HasColumnType("text")
                        .HasColumnName("producer_ean");

                    b.Property<string>("ConsumerEan")
                        .HasColumnType("text")
                        .HasColumnName("consumer_ean");

                    b.Property<DateTimeOffset>("TimeFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_from");

                    b.Property<double>("KwhShared")
                        .HasColumnType("double precision")
                        .HasColumnName("kwh_shared");

                    b.Property<DateTimeOffset>("TimeTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_to");

                    b.HasKey("TenantId", "ProducerEan", "ConsumerEan", "TimeFrom");

                    b.ToTable("edc_link_readings", (string)null);
                });

            modelBuilder.Entity("Edc.Backend.Api.Infrastructure.Persistence.EdcReading", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Ean")
                        .HasColumnType("text")
                        .HasColumnName("ean");

                    b.Property<DateTimeOffset>("TimeFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_from");

                    b.Property<bool>("IsProducer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_producer");

                    b.Property<double>("KwhMissed")
                        .HasColumnType("double precision")
                        .HasColumnName("kwh_missed");

                    b.Property<double>("KwhRemainder")
                        .HasColumnType("double precision")
                        .HasColumnName("kwh_remainder");

                    b.Property<double>("KwhTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("kwh_total");

                    b.Property<DateTimeOffset>("TimeTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_to");

                    b.HasKey("TenantId", "Ean", "TimeFrom");

                    b.ToTable("edc_readings", (string)null);
                });

            modelBuilder.Entity("Edc.Backend.Api.Infrastructure.Persistence.OtpCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("bigint")
                        .HasColumnName("expires_at");

                    b.Property<long?>("UsedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("used_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("otp_codes", (string)null);
                });

            modelBuilder.Entity("Edc.Backend.Api.Infrastructure.Persistence.PriorityLink", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ProducerEan")
                        .HasColumnType("text")
                        .HasColumnName("producer_ean");

                    b.Property<string>("ConsumerEan")
                        .HasColumnType("text")
                        .HasColumnName("consumer_ean");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.HasKey("TenantId", "ProducerEan", "ConsumerEan");

                    b.ToTable("priority_links", (string)null);
                });

            modelBuilder.Entity("Edc.Backend.Api.Infrastructure.Persistence.Session", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("bigint")
                        .HasColumnName("last_seen_at");

                    b.Property<long?>("RevokedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("revoked_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("TokenHash");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Edc.Backend.Api.Infrastructure.Persistence.SyntheticEan", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Ean")
                        .HasColumnType("text")
                        .HasColumnName("ean");

                    b.Property<double?>("AnnualKwh")
                        .HasColumnType("double precision")
                        .HasColumnName("annual_kwh");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<double?>("InstalledKw")
                        .HasColumnType("double precision")
                        .HasColumnName("installed_kw");

                    b.Property<bool>("IsProducer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_producer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("TdzCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tdz_category");

                    b.HasKey("TenantId", "Ean");

                    b.ToTable("synthetic_eans", (string)null);
                });

            modelBuilder.Entity("Edc.Backend.Api.Infrastructure.Persistence.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Edc.Backend.Api.Infrastructure.Persistence.TenantAdmin", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.HasKey("TenantId", "UserId");

                    b.ToTable("tenant_admins", (string)null);
                });

            modelBuilder.Entity("Edc.Backend.Api.Infrastructure.Persistence.TenantEan", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Ean")
                        .HasColumnType("text")
                        .HasColumnName("ean");

                    b.Property<long>("ImportedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("imported_at");

                    b.Property<int>("IsPublic")
                        .HasColumnType("integer")
                        .HasColumnName("is_public");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("member_name");

                    b.HasKey("TenantId", "Ean");

                    b.ToTable("tenant_eans", (string)null);
                });

            modelBuilder.Entity("Edc.Backend.Api.Infrastructure.Persistence.TenantEdcCredential", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TenantId"));

                    b.Property<string>("EdcEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("edc_email");

                    b.Property<string>("EdcPasswordEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("edc_password_encrypted");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId");

                    b.ToTable("tenant_edc_credentials", (string)null);
                });

            modelBuilder.Entity("Edc.Backend.Api.Infrastructure.Persistence.TenantEdcImport", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TenantId"));

                    b.Property<int>("ConsumerCount")
                        .HasColumnType("integer")
                        .HasColumnName("consumer_count");

                    b.Property<string>("CsvText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("csv_text");

                    b.Property<long>("DateFrom")
                        .HasColumnType("bigint")
                        .HasColumnName("date_from");

                    b.Property<long>("DateTo")
                        .HasColumnType("bigint")
                        .HasColumnName("date_to");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<long>("ImportedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("imported_at");

                    b.Property<int>("IntervalCount")
                        .HasColumnType("integer")
                        .HasColumnName("interval_count");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<int>("ProducerCount")
                        .HasColumnType("integer")
                        .HasColumnName("producer_count");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_hash");

                    b.HasKey("TenantId");

                    b.ToTable("tenant_edc_imports", (string)null);
                });

            modelBuilder.Entity("Edc.Backend.Api.Infrastructure.Persistence.TenantEdcLinkImport", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TenantId"));

                    b.Property<string>("CsvText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("csv_text");

                    b.Property<long>("DateFrom")
                        .HasColumnType("bigint")
                        .HasColumnName("date_from");

                    b.Property<long>("DateTo")
                        .HasColumnType("bigint")
                        .HasColumnName("date_to");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<long>("ImportedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("imported_at");

                    b.Property<int>("IntervalCount")
                        .HasColumnType("integer")
                        .HasColumnName("interval_count");

                    b.Property<int>("LinkCount")
                        .HasColumnType("integer")
                        .HasColumnName("link_count");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_hash");

                    b.HasKey("TenantId");

                    b.ToTable("tenant_edc_link_imports", (string)null);
                });

            modelBuilder.Entity("Edc.Backend.Api.Infrastructure.Persistence.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<long?>("ImportedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("imported_at");

                    b.Property<int>("IsActive")
                        .HasColumnType("integer")
                        .HasColumnName("is_active");

                    b.Property<string>("Mesto")
                        .HasColumnType("text")
                        .HasColumnName("mesto");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Typ")
                        .HasColumnType("text")
                        .HasColumnName("typ");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Edc.Backend.Api.Infrastructure.Persistence.UserEan", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("Ean")
                        .HasColumnType("text")
                        .HasColumnName("ean");

                    b.Property<long>("ImportedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("imported_at");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("member_name");

                    b.HasKey("UserId", "Ean");

                    b.ToTable("user_eans", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
